config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  resources :subjects
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "courses#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher

  has_many :courses
  has_many :students, through: :courses
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
    @subject = Subject.find([params[:id]])
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name, :unit, :teacher_id)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: inline" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :unit, style: "display: inline" %>
    <%= form.number_field :unit %>
  </div>

  <div class="field">
    <%= form.label "Choose a teacher:", style: "display: inline" %>
    <%= collection_select(:subject, :teacher_id, Teacher.all, :id, :name) %>
  </div>
   <div class="not-found">
    <p><i>Teacher not found? 
      <span><%= link_to "Create now...", new_teacher_path %></span>
    </i></p>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <p class="field">
    <strong>Subject Name: </strong><%= subject.name %>
  </p>

  <p class="field">
    <strong>Unit:</strong>
    <%= subject.unit %>
  </p>

  <p class="field">
    <strong>Teacher:</strong>
    <%= subject.teacher.name %>
  </p>

</div>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<div style="margin-left:10px;">
  <%= render "form", subject: @subject %>
</div>
<br>

<div>
  <%= link_to "Show this subject", @subject %> |
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subjects</h1>

<div id="subjects">
  <table>
    <thead>
      <th>Subject Name</th>
      <th>Units</th>
      <th>Teacher</th>
    </thead>
    <tbody>
       <% @subjects.each do |subject| %>
       <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.unit %></td>
          <td><%= subject.teacher.name %></td>
       </tr>
       <%end%>
    </tbody>
  </table>
</div>
<br>
<%= link_to "New subject", new_subject_path %>

app/views/subjects/new.html.erb
<h1>Create a New subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subject %>

<div class="field">
  <%= link_to "Edit this subject", edit_subject_path(@subject) %> |
  <%= link_to "Back to subjects", subjects_path %>
  <div style="margin-top: 10px;">
    <%= button_to "Delete this subject", @subject, method: :delete %>
  </div>
 
</div>