config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  resources :subjects
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "courses#index"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :subjects
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
    @teacher = Teacher.find([params[:id]])
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :department_name)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Name: ", style: "display: inline" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Department Name: ", style: "display: inline" %>
    <%= form.text_field :department_name %>
  </div>

  <div style="margin-left: 10px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p class="field">
    <strong>Name of Teacher:</strong><span>
        <%= teacher.name %>
    </span>
  </p>

  <p class="field">
    <strong>Department name:</strong>
    <%= teacher.department_name %>
  </p>

</div>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Teachers</h1>

<div id="teachers">
  <table>
    <thead>
      <th>Teacher Name</th>
      <th>Department Name</th>
    </thead>
    <tbody>
       <% @teachers.each do |teacher| %>
       <tr>
        <td> <%= link_to teacher.name, teacher %></td>
        <td> <%= teacher.department_name%></td>
       </tr>
       <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to "New teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>

<div class="field">
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>
    <div style="margin-top: 10px;">
  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
  </div>
</div>