config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  resources :subjects
  resources :teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "courses#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
    @subjects = Subject.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_url, notice: "Course was successfully created." }
        format.json { render :index, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to courses_url, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Student was successfully unenrolled." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:subject_id, :student_id, :name)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p class="field">
    <strong>Course Subject:</strong>
    <%= course.subject.name %>
  </p>

  <p class="field">
    <strong>Student:</strong>
    <%= course.student.name %>
  </p>


</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label "Choose a subject: ", style: "display: inline" %>
    <%= collection_select(:course, :subject_id, Subject.all, :id, :name) %>
 </div>

  <div class="not-found">
      <p><i>Subject not found? 
        <span><%= link_to "Create now...", new_subject_path %></span>
      </i></p>
  </div>

  <div class="field">
    <%= form.label :student_id, style: "display: inline" %>
    <%= collection_select(:course, :student_id, Student.all, :id, :name) %>
  </div>

  <div class="not-found">
    <p><i>Student not found? 
      <span><%= link_to "Create now...", new_student_path %></span>
    </i></p>
  </div>


  <div style="margin: 10px;">
    <%= form.submit "Enrol Student"%>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrollment</h1>
<h4>List of Courses: </h4>
<div id="courses">
  <ul>
    <% @subjects.each do |subject| %>
    <li>
      <b><%= link_to subject.name, subject%></b>
        <table style="margin-top:5px;">
          <th>
            <tr>
              <td>Name of Student</td>
              <td>Year Level</td>
            </tr>
          </th>
          <tbody>
              <% @courses.each do |course| %>
              <% if course.subject_id == subject.id %>
              <tr>
                <td>  <%= link_to course.student.name, course %> </td>
                <td>  <%= course.student.year_level %> </td>
              </tr>
              <% end %> 
              <% end %> 
              <tr><td colspan="2">
                 <i><%= link_to "Enroll a student in this course...", new_course_path %></i>
              </td></tr>
          </tbody>
        </table>
    </li>
    <br>
    <% end %> 
  </ul>

  <div class="not-found">
    <p><i>Course not found?  
      <span><%= link_to "Create", new_subject_path %></span> 
      a subject first.
    </i></p>
  </div>
</div>

app/views/courses/new.html.erb
<div>
  <%= link_to "Back to courses", courses_path %>
</div>

<h1>Enroll A Student to a Course</h1>

<%= render "form", course: @course %>

<br>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>
<div class="field">
  <%= link_to "Edit enrollment details", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <div style="margin-top: 10px;">
    <%= button_to "Unenrol student", @course, method: :delete %>
  </div>
</div>